SELECT
	condition_occurrence_id AS device_exposure_id,
	person_id AS person_id,
	condition_concept_id AS device_concept_id,
	condition_start_date AS device_exposure_start_date,
	condition_start_datetime AS device_exposure_start_datetime,
	condition_end_date AS device_exposure_end_date,
	condition_end_datetime AS device_exposure_end_datetime,
	condition_type_concept_id AS device_type_concept_id,
	NULL AS unique_device_id,
	NULL AS production_id,
	NULL AS quantity,
	provider_id AS provider_id,
	visit_occurrence_id AS visit_occurrence_id,
	visit_detail_id AS visit_detail_id,
	condition_source_value AS device_source_value,
	condition_source_concept_id AS device_source_concept_id,
	0 AS unit_concept_id,
	NULL AS unit_source_value,
	0 AS unit_source_concept_id
FROM read_parquet('@CONDITION_OCCURRENCE')