SELECT
	drug_exposure_id AS measurement_id,
	person_id AS person_id,
	drug_concept_id AS measurement_concept_id,
	drug_exposure_start_date AS measurement_date,
	drug_exposure_start_datetime AS measurement_datetime,
	drug_exposure_start_datetime AS measurement_time,
	drug_type_concept_id AS measurement_type_concept_id,
	0 AS operator_concept_id,
	NULL AS value_as_number,
	COALESCE(vh_value_as_concept_id, 0) AS value_as_concept_id,
	0 AS unit_concept_id,
	NULL AS range_low,
	NULL AS range_high,
	provider_id AS provider_id,
	visit_occurrence_id AS visit_occurrence_id,
	visit_detail_id AS visit_detail_id,
	drug_source_value AS measurement_source_value,
	drug_source_concept_id AS measurement_source_concept_id,
	NULL AS unit_source_value,
	0 AS unit_source_concept_id,
	NULL AS value_source_value,
	NULL AS measurement_event_id,
	0 AS meas_event_field_concept_id
FROM read_parquet('@DRUG_EXPOSURE')