SELECT
	drug_exposure_id AS drug_exposure_id,
	person_id AS person_id,
	drug_concept_id AS drug_concept_id,
	drug_exposure_start_date AS drug_exposure_start_date,
	drug_exposure_start_datetime AS drug_exposure_start_datetime,
	drug_exposure_end_date AS drug_exposure_end_date,
	drug_exposure_end_datetime AS drug_exposure_end_datetime,
	verbatim_end_date AS verbatim_end_date,
	drug_type_concept_id AS drug_type_concept_id,
	stop_reason AS stop_reason,
	refills AS refills,
	quantity AS quantity,
	days_supply AS days_supply,
	sig AS sig,
	route_concept_id AS route_concept_id,
	lot_number AS lot_number,
	provider_id AS provider_id,
	visit_occurrence_id AS visit_occurrence_id,
	visit_detail_id AS visit_detail_id,
	drug_source_value AS drug_source_value,
	drug_source_concept_id AS drug_source_concept_id,
	route_source_value AS route_source_value,
	dose_unit_source_value AS dose_unit_source_value
FROM read_parquet('@DRUG_EXPOSURE')