SELECT
	measurement_id AS observation_id,
	person_id AS person_id,
	measurement_concept_id AS observation_concept_id,
	measurement_date AS observation_date,
	measurement_datetime AS observation_datetime,
	measurement_type_concept_id AS observation_type_concept_id,
	value_as_number AS value_as_number,
	NULL AS value_as_string,
	COALESCE(vh_value_as_concept_id, value_as_concept_id, 0) AS value_as_concept_id,
	0 AS qualifier_concept_id,
	unit_concept_id AS unit_concept_id,
	provider_id AS provider_id,
	visit_occurrence_id AS visit_occurrence_id,
	visit_detail_id AS visit_detail_id,
	measurement_source_value AS observation_source_value,
	measurement_source_concept_id AS observation_source_concept_id,
	unit_source_value AS unit_source_value,
	NULL AS qualifier_source_value,
	value_source_value AS value_source_value,
	measurement_event_id AS observation_event_id,
	meas_event_field_concept_id AS obs_event_field_concept_id
FROM read_parquet('@MEASUREMENT')