SELECT
	observation_id AS measurement_id,
	person_id AS person_id,
	observation_concept_id AS measurement_concept_id,
	observation_date AS measurement_date,
	observation_datetime AS measurement_datetime,
	observation_datetime AS measurement_time,
	observation_type_concept_id AS measurement_type_concept_id,
	0 AS operator_concept_id,
	value_as_number AS value_as_number,
	COALESCE(vh_value_as_concept_id, value_as_concept_id, 0) AS value_as_concept_id,
	unit_concept_id AS unit_concept_id,
	NULL AS range_low,
	NULL AS range_high,
	provider_id AS provider_id,
	visit_occurrence_id AS visit_occurrence_id,
	visit_detail_id AS visit_detail_id,
	observation_source_value AS measurement_source_value,
	observation_source_concept_id AS measurement_source_concept_id,
	unit_source_value AS unit_source_value,
	0 AS unit_source_concept_id,
	value_source_value AS value_source_value,
	observation_event_id AS measurement_event_id,
	obs_event_field_concept_id AS meas_event_field_concept_id
FROM read_parquet('@OBSERVATION')