SELECT
	specimen_id AS drug_exposure_id,
	person_id AS person_id,
	specimen_concept_id AS drug_concept_id,
	specimen_date AS drug_exposure_start_date,
	specimen_datetime AS drug_exposure_start_datetime,
	specimen_date AS drug_exposure_end_date,
	NULL AS drug_exposure_end_datetime,
	NULL AS verbatim_end_date,
	specimen_type_concept_id AS drug_type_concept_id,
	NULL AS stop_reason,
	NULL AS refills,
	NULL AS quantity,
	NULL AS days_supply,
	NULL AS sig,
	0 AS route_concept_id,
	NULL AS lot_number,
	NULL AS provider_id,
	NULL AS visit_occurrence_id,
	NULL AS visit_detail_id,
	specimen_source_value AS drug_source_value,
	0 AS drug_source_concept_id,
	NULL AS route_source_value,
	NULL AS dose_unit_source_value
FROM read_parquet('@SPECIMEN')