SELECT
	specimen_id AS observation_id,
	person_id AS person_id,
	specimen_concept_id AS observation_concept_id,
	specimen_date AS observation_date,
	specimen_datetime AS observation_datetime,
	specimen_type_concept_id AS observation_type_concept_id,
	NULL AS value_as_number,
	NULL AS value_as_string,
	COALESCE(vh_value_as_concept_id, 0) AS value_as_concept_id,
	0 AS qualifier_concept_id,
	unit_concept_id AS unit_concept_id,
	NULL AS provider_id,
	NULL AS visit_occurrence_id,
	NULL AS visit_detail_id,
	specimen_source_value AS observation_source_value,
	0 AS observation_source_concept_id,
	unit_source_value AS unit_source_value,
	NULL AS qualifier_source_value,
	NULL AS value_source_value,
	NULL AS observation_event_id,
	0 AS obs_event_field_concept_id
FROM read_parquet('@SPECIMEN')