SELECT
	specimen_id AS measurement_id,
	person_id AS person_id,
	specimen_concept_id AS measurement_concept_id,
	specimen_date AS measurement_date,
	specimen_datetime AS measurement_datetime,
	specimen_datetime AS measurement_time,
	specimen_type_concept_id AS measurement_type_concept_id,
	0 AS operator_concept_id,
	NULL AS value_as_number,
	COALESCE(vh_value_as_concept_id, 0) AS value_as_concept_id,
	unit_concept_id AS unit_concept_id,
	NULL AS range_low,
	NULL AS range_high,
	NULL AS provider_id,
	NULL AS visit_occurrence_id,
	NULL AS visit_detail_id,
	NULL AS measurement_source_value,
	0 AS measurement_source_concept_id,
	unit_source_value AS unit_source_value,
	0 AS unit_source_concept_id,
	NULL AS value_source_value,
	NULL AS measurement_event_id,
	0 AS meas_event_field_concept_id
FROM read_parquet('@SPECIMEN')