SELECT
	visit_occurrence_id AS drug_exposure_id,
	person_id AS person_id,
	visit_concept_id AS drug_concept_id,
	visit_start_date AS drug_exposure_start_date,
	visit_start_datetime AS drug_exposure_start_datetime,
	visit_end_date AS drug_exposure_end_date,
	visit_end_datetime AS drug_exposure_end_datetime,
	NULL AS verbatim_end_date,
	visit_type_concept_id AS drug_type_concept_id,
	NULL AS stop_reason,
	NULL AS refills,
	NULL AS quantity,
	NULL AS days_supply,
	NULL AS sig,
	0 AS route_concept_id,
	NULL AS lot_number,
	provider_id AS provider_id,
	NULL AS visit_occurrence_id,
	NULL AS visit_detail_id,
	visit_source_value AS drug_source_value,
	visit_source_concept_id AS drug_source_concept_id,
	NULL AS route_source_value,
	NULL AS dose_unit_source_value
FROM read_parquet('@VISIT_OCCURRENCE')