SELECT
	visit_occurrence_id AS observation_id,
	person_id AS person_id,
	visit_concept_id AS observation_concept_id,
	visit_start_date AS observation_date,
	visit_start_datetime AS observation_datetime,
	visit_type_concept_id AS observation_type_concept_id,
	NULL AS value_as_number,
	NULL AS value_as_string,
	vh_value_as_concept_id AS value_as_concept_id,
	0 AS qualifier_concept_id,
	0 AS unit_concept_id,
	provider_id AS provider_id,
	NULL AS visit_occurrence_id,
	NULL AS visit_detail_id,
	visit_source_value AS observation_source_value,
	visit_source_concept_id AS observation_source_concept_id,
	NULL AS unit_source_value,
	NULL AS qualifier_source_value,
	NULL AS value_source_value,
	NULL AS observation_event_id,
	0 AS obs_event_field_concept_id
FROM read_parquet('@VISIT_OCCURRENCE')