SELECT 
    device_exposure_id,
    person_id,
    device_concept_id,
    device_exposure_start_date,
    device_exposure_start_datetime,
    device_exposure_end_date,
    device_exposure_end_datetime,
    device_type_concept_id,
    unique_device_id,
    CAST(NULL AS VARCHAR) AS production_id,
    quantity,
    provider_id,
    visit_occurrence_id,
    visit_detail_id,
    device_source_value,
    device_source_concept_id,
    CAST(NULL AS BIGINT) AS unit_concept_id,
    CAST(NULL AS VARCHAR) AS unit_source_value,
    CAST(NULL AS BIGINT) AS unit_source_concept_id